version: "3"

# dotenv:
#   - .env

vars:
  APP_NAME: server
  CMD_PATH: ./cmd/server
  MIGRATE_CMD_PATH: ./cmd/migrate
  BIN_DIR: ./bin
  MIGRATIONS_DIR: ./migrations

tasks:
  run:
    desc: Run the Go server
    cmds:
      - go run {{.CMD_PATH}}

  build:
    desc: Build the Go server
    cmds:
      - go build -o {{.BIN_DIR}}/{{.APP_NAME}}.exe {{.CMD_PATH}}

  test:
    desc: Run all tests
    cmds:
      - go test ./...

  fmt:
    desc: Format Go code
    cmds:
      - go fmt ./...

  vet:
    desc: Run Go vet
    cmds:
      - go vet ./...

  tidy:
    desc: Clean Go dependencies
    cmds:
      - go mod tidy

  check:
    desc: Run format, vet and tests
    cmds:
      - go fmt ./...
      - go vet ./...
      - go test ./...

  migrate-create:
    desc: Create a new migration
    cmds:
      - go run {{.MIGRATE_CMD_PATH}} create {{.CLI_ARGS}}

  migrate-up:
    desc: Run all database migrations
    cmds:
      - go run {{.MIGRATE_CMD_PATH}} up

  migrate-down:
    desc: Rollback the last database migration
    cmds:
      - go run {{.MIGRATE_CMD_PATH}} down

  migrate-down-all:
    desc: Rollback all database migrations
    cmds:
      - go run {{.MIGRATE_CMD_PATH}} down-all --confirm

  clean:
    desc: Remove build files
    cmds:
      - powershell -Command "if (Test-Path '{{.BIN_DIR}}') { Remove-Item '{{.BIN_DIR}}' -Recurse -Force }"
